# Generated by Django 4.1.3 on 2022-11-15 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='present',
            name='reserved',
            field=models.BooleanField(default=False),
        ),
    ]
