# Generated by Django 4.1.3 on 2022-12-14 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishes', '0002_present_reserved'),
    ]

    operations = [
        migrations.AddField(
            model_name='present',
            name='reserver',
            field=models.IntegerField(default=1),
        ),
    ]
